version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flask_bot
    restart: always
    ports:
      - "7401:5080"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge